export const AUTH_START = "AUTH_START";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const NORMAL_FAIL = "NORMAL_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOAD_INFORMATION = "LOAD_INFORMATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const FETCH_USER_NAMES = "FETCH_USER_NAMES";
export const FETCH_USER_NAMES_ERROR = "FETCH_USER_NAMES_ERROR";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const APPLY_TO_POSITION = "APPLY_TO_POSITION";
export const APPLY_TO_POSITION_ERROR = "APPLY_TO_POSITION_ERROR";

export const UPLOAD_RESUME = "UPLOAD_RESUME";
export const UPLOAD_RESUME_ERROR = "UPLOAD_RESUME_ERROR";

export const RELEASE_POSITION = "RELEASE_POSITION";
export const RELEASE_POSITION_ERROR = "RELEASE_POSITION_ERROR";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_MESSAGE_ERROR = "CREATE_MESSAGE_ERROR";

export const CREATE_NOTICE = "CREATE_NOTICE";
export const CREATE_NOTICE_ERROR = "CREATE_NOTICE_ERROR";

export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const CREATE_FEEDBACK_ERROR = "CREATE_FEEDBACK_ERROR";

export const CREATE_POSITION = "CREATE_POSITION";
export const CREATE_POSITION_ERROR = "CREATE_POSITION_ERROR";

export const LOAD_POSITION = "LOAD_POSITION";
export const LOAD_POSITION_ERROR = "LOAD_POSITION_ERROR";

export const LOAD_APPLICATION = "LOAD_APPLICATION";
export const LOAD_APPLICATION_ERROR = "LOAD_APPLICATION_ERROR";

export const SELECT_APPLICATION = "SELECT_APPLICATION";
export const UPDATE_PROFILE = "UPDATE_PROFILE";


